language: c
cache: ccache

notifications:
  irc:
    channels:
      - "irc.oftc.net#cad"
    on_success: change
    on_failure: change
    skip_join: true
    template:
      - "%{repository_slug}(%{author}): %{message} %{build_url}"

sudo: false
dist: trusty

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - gettext
    - intltool
    - valgrind
    - libgtk2.0-dev
    - pidgin-dev
    - libpurple-dev

before_install:
  - PREFIX=/tmp/prefix # we dont want to use sudo (and be forced to use the non-container based infrastructure)
  - mkdir -p ${PREFIX}
  - export LD_LIBRARY_PATH=${PREFIX}/lib:${LD_LIBRARY_PATH}
  - export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"
  - wget https://sourceforge.net/projects/pidgin/files/Pidgin/2.13.0/pidgin-2.13.0.tar.bz2/download -O ${PREFIX}/pidgin.tar.bz2
  - pushd ${PREFIX} && tar xjvf pidgin.tar.bz2 && popd
  - mkdir .deps
  - git clone --depth=1 https://bugs.otr.im/lib/libotr.git .deps/libotr
  - pushd .deps/libotr && ./bootstrap && ./configure --prefix=$PREFIX && make && make install && popd
  # Dependencies for libotr-ng
  - curl https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.26.tar.bz2 | tar xjf - -C .deps
  - pushd .deps/libgpg-error-1.26 && ./configure --prefix=$PREFIX && make && make install && popd
  - curl https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.1.tar.bz2 | tar xjf - -C .deps
  - pushd .deps/libgcrypt-1.8.1 && ./configure --with-libgpg-error-prefix=$PREFIX --prefix=$PREFIX && make && make install && popd
  - curl https://download.libsodium.org/libsodium/releases/old/libsodium-1.0.11.tar.gz | tar xzf - -C .deps
  - pushd .deps/libsodium-1.0.11 && ./autogen.sh && ./configure --prefix=$PREFIX && make && make install && popd
  - git clone --depth=1 https://github.com/otrv4/libgoldilocks .deps/libgoldilocks
  - pushd .deps/libgoldilocks && ./autogen.sh && ./configure --prefix=$PREFIX && make && make install && popd
  - git clone --depth=1 https://github.com/otrv4/libotr-ng.git .deps/libotr-ng
  - pushd .deps/libotr-ng && ./autogen.sh && ./configure --with-libotr-inc-prefix=${PREFIX}/include --with-libotr-prefix=${PREFIX}/lib --with-libgcrypt-prefix=$PREFIX --prefix=$PREFIX && make && make install && popd

script:
  - cd ${PREFIX}/pidgin-2.13.0/pidgin/plugins
  - mv ${TRAVIS_BUILD_DIR} ${PREFIX}/pidgin-2.13.0/pidgin/plugins/
  - TRAVIS_BUILD_DIR=${PREFIX}/pidgin-2.13.0/pidgin/plugins/`basename ${TRAVIS_BUILD_DIR}`
  - cd ${TRAVIS_BUILD_DIR}
  - echo -e "ACLOCAL_FLAGS= -I ${PREFIX}/share/aclocal\n$(cat Makefile.am)" > Makefile.am
  - ./autogen.sh
  - ./configure --with-libotr-inc-prefix=${PREFIX}/include --with-libotr-prefix=${PREFIX}/lib
  - make && make test

