language: c
cache:
  - ccache: true
  - directories:
      - .deps

notifications:
  irc:
    channels:
      - "irc.oftc.net#cad"
    on_success: change
    on_failure: change
    skip_join: true
    template:
      - "%{repository_slug}(%{author}): %{message} %{build_url}"

sudo: false
dist: trusty

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - gettext
    - intltool
    - valgrind
    - libgtk2.0-dev
    - pidgin-dev
    - libpurple-dev

before_install:
  - PREFIX=/tmp/prefix # we dont want to use sudo (and be forced to use the non-container based infrastructure)
  - mkdir -p ${PREFIX}
  - export LD_LIBRARY_PATH=${PREFIX}/lib:${LD_LIBRARY_PATH}
  - export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"
  - ./travis_before_script.sh
  - git clone --depth=1 https://github.com/otrv4/libotr-ng.git .deps/libotr-ng
  - pushd .deps/libotr-ng && ./autogen.sh && ./configure --with-libotr-inc-prefix=${PREFIX}/include --with-libotr-prefix=${PREFIX}/lib --with-libgcrypt-prefix=$PREFIX --prefix=$PREFIX && make && make install && popd

script:
  - cd ${PREFIX}/pidgin-2.13.0/pidgin/plugins
  - mv ${TRAVIS_BUILD_DIR} ${PREFIX}/pidgin-2.13.0/pidgin/plugins/
  - TRAVIS_BUILD_DIR=${PREFIX}/pidgin-2.13.0/pidgin/plugins/`basename ${TRAVIS_BUILD_DIR}`
  - cd ${TRAVIS_BUILD_DIR}
  - echo -e "ACLOCAL_FLAGS= -I ${PREFIX}/share/aclocal\n$(cat Makefile.am)" > Makefile.am
  - ./autogen.sh
  - ./configure --with-libotr-inc-prefix=${PREFIX}/include --with-libotr-prefix=${PREFIX}/lib
  - make && make test
